<head>
<meta charset="UTF-8">
<link rel="icon" href="32x32.bmp" sizes="32x32" type="image/png">
<title>毕业纪念</title>
<style>
        body {
            margin: 0;
            padding: 0;
            background-image:url('qiangzhi.jpg');
        }
        header {
            background-color: #FF9933;
            padding: 10px;
            text-align: center;
        }
        nav {
            background-color: #FF6633;
            padding: 10px;
            text-align: center;
        }
        nav a {
            color: #fff;
            text-decoration: none;
            padding: 0.125px 2.5px;
        }
        nav a:hover {
            background-color: #FF6633;
        }
        main {
            padding: 20px;
        }
        img {
            max-width: 100%;
            height: auto;
            display: block;
            margin: 0 auto;
        }
        footer {
            background-color: #FF9933;
            color: #fff;
            padding: 10px;
            text-align: center;
        }
</style>
</head>
